include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    sort_pub_dependencies: ignore
  exclude:
    - "**/firebase_options_*.dart"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/color/**"
    - "**/gen/**"
    - "**/cmd/**"
    - lib/core/model/**

linter:
  rules:
    public_member_api_docs: false
    no_default_cases: false
    one_member_abstracts: false
