include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    sort_pub_dependencies: ignore
  exclude:
    - "**/gen/*.dart"
    - "**/firebase_options_*.dart"
    - "**/*.freezed.dart"  
    - "**/*.g.dart" 
    
linter:
  rules:
    # dont need all doc
   public_member_api_docs: false
    

   
   