name: core_model
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  riverpod_annotation: 2.6.1
  riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.6.1
  riverpod_generator: ^2.6.3
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
