// Mocks generated by Mockito 5.4.4 from annotations
// in melos_template/test/helper/helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:connectivity_plus/connectivity_plus.dart' as _i6;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i7;
import 'package:core_service/firebase/firebase_messaging/firebase_messaging_service.dart'
    as _i8;
import 'package:core_service/notification/notification_service.dart' as _i9;
import 'package:firebase_messaging/firebase_messaging.dart' as _i3;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i10;
import 'package:melos_template/core/model/weater/weater_data/weather_data.dart'
    as _i2;
import 'package:melos_template/core/network/api_client/weather_api_client.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherData_0 extends _i1.SmartFake implements _i2.WeatherData {
  _FakeWeatherData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseMessaging_1 extends _i1.SmartFake
    implements _i3.FirebaseMessaging {
  _FakeFirebaseMessaging_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherApiClient extends _i1.Mock implements _i4.WeatherApiClient {
  @override
  _i5.Future<_i2.WeatherData> getCurrentWeather(
    String? city,
    String? apiKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [
            city,
            apiKey,
          ],
        ),
        returnValue: _i5.Future<_i2.WeatherData>.value(_FakeWeatherData_0(
          this,
          Invocation.method(
            #getCurrentWeather,
            [
              city,
              apiKey,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.WeatherData>.value(_FakeWeatherData_0(
          this,
          Invocation.method(
            #getCurrentWeather,
            [
              city,
              apiKey,
            ],
          ),
        )),
      ) as _i5.Future<_i2.WeatherData>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i6.Connectivity {
  @override
  _i5.Stream<List<_i7.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i5.Stream<List<_i7.ConnectivityResult>>.empty(),
        returnValueForMissingStub:
            _i5.Stream<List<_i7.ConnectivityResult>>.empty(),
      ) as _i5.Stream<List<_i7.ConnectivityResult>>);

  @override
  _i5.Future<List<_i7.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i5.Future<List<_i7.ConnectivityResult>>.value(
            <_i7.ConnectivityResult>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i7.ConnectivityResult>>.value(
                <_i7.ConnectivityResult>[]),
      ) as _i5.Future<List<_i7.ConnectivityResult>>);
}

/// A class which mocks [FirebaseMessagingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessagingService extends _i1.Mock
    implements _i8.FirebaseMessagingService {
  @override
  _i5.Stream<_i3.RemoteMessage> get messageStream => (super.noSuchMethod(
        Invocation.getter(#messageStream),
        returnValue: _i5.Stream<_i3.RemoteMessage>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.RemoteMessage>.empty(),
      ) as _i5.Stream<_i3.RemoteMessage>);

  @override
  _i5.Stream<_i3.RemoteMessage> get openedAppStream => (super.noSuchMethod(
        Invocation.getter(#openedAppStream),
        returnValue: _i5.Stream<_i3.RemoteMessage>.empty(),
        returnValueForMissingStub: _i5.Stream<_i3.RemoteMessage>.empty(),
      ) as _i5.Stream<_i3.RemoteMessage>);

  @override
  _i5.Stream<String> get tokenStream => (super.noSuchMethod(
        Invocation.getter(#tokenStream),
        returnValue: _i5.Stream<String>.empty(),
        returnValueForMissingStub: _i5.Stream<String>.empty(),
      ) as _i5.Stream<String>);

  @override
  _i5.Future<String?> get token => (super.noSuchMethod(
        Invocation.getter(#token),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> subscribeToTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #subscribeToTopic,
          [topic],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> unsubscribeFromTopic(String? topic) => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromTopic,
          [topic],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i9.NotificationService {
  @override
  _i3.FirebaseMessaging get firebaseMessaging => (super.noSuchMethod(
        Invocation.getter(#firebaseMessaging),
        returnValue: _FakeFirebaseMessaging_1(
          this,
          Invocation.getter(#firebaseMessaging),
        ),
        returnValueForMissingStub: _FakeFirebaseMessaging_1(
          this,
          Invocation.getter(#firebaseMessaging),
        ),
      ) as _i3.FirebaseMessaging);

  @override
  List<_i10.AndroidNotificationChannelGroup> get notificationChannelGroups =>
      (super.noSuchMethod(
        Invocation.getter(#notificationChannelGroups),
        returnValue: <_i10.AndroidNotificationChannelGroup>[],
        returnValueForMissingStub: <_i10.AndroidNotificationChannelGroup>[],
      ) as List<_i10.AndroidNotificationChannelGroup>);

  @override
  List<_i10.AndroidNotificationChannel> get notificationChannels =>
      (super.noSuchMethod(
        Invocation.getter(#notificationChannels),
        returnValue: <_i10.AndroidNotificationChannel>[],
        returnValueForMissingStub: <_i10.AndroidNotificationChannel>[],
      ) as List<_i10.AndroidNotificationChannel>);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setupFlutterNotifications() => (super.noSuchMethod(
        Invocation.method(
          #setupFlutterNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> showNotification(_i3.RemoteMessage? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [message],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
