name: check

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: install fvm
        run: |
            brew tap leoafarias/fvm
            brew install fvm

      - name: set up fvm
        run: |
          fvm install

      - name:  Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: set up dart
        run: |
          fvm dart --version

      - name: Set up Melos
        run: |
          fvm dart pub global activate melos

      - name: melso bootstrap
        run: |
          fvm dart pub global run melos bootstrap


      - name: Run flutter analyze
        shell: bash
        run: |
          melos analyze

      - name: Remove matcher
        if: always()
        run: echo "::remove-matcher owner=dart-analyzer::"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        if: always()
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Danger
        uses: MeilCli/danger-action@1996610a4c089e3a79bf3131a70c3c1b311e32f9
        if: always()
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: test
        run: |
          melos test

