name: Coding Check when PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      flutter: ${{ steps.filter.outputs.flutter }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Filter by paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            flutter:
              - '**/android/**'
              - '**/assets/**'
              - '**/gen/**'
              - '**/dart_defines/**'
              - '**/ios/**'
              - '**/lib/**'
              - '**/test/**'
              - '**/web/**'
              - '**/analysis_options.yaml'
              - '**/melos.yaml'
              - '**/mason.yaml'
              - '**/pubspec.yaml'
              - '.fvmrc'

  analyze:
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter with FVM
        id: setup-flutter
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3

      - name: Prepare Melos
        run: echo "MELOS_SDK_PATH=${{ env.FLUTTER_ROOT }}" >> "$GITHUB_ENV"

      - name: Install Melos
        uses: bluefireteam/melos-action@v3    
      
      - name: Install matcher
        run: echo "::add-matcher::.github/analyzer-problem-matcher.json"

      - name: Run linter
        run: flutter analyze > flutter_analyze_report.txt

      - name: Remove matcher
        if: always()
        run: echo "::remove-matcher owner=dart-analyzer::"
      
      - name: Run flutter analyze
        run: flutter analyze > flutter_analyze_report.txt
        continue-on-error: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        if: always()
        with:
          ruby-version: '2.7'
          bundler-cache: true
              
      - name: Danger
        uses: MeilCli/danger-action@v5
        if: always()
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  # test:
  #   needs: check
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 20
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Flutter with FVM
  #       id: setup-flutter
  #       uses: kuhnroyal/flutter-fvm-config-action/setup@v3

  #     - name: Prepare Melos
  #       run: echo "MELOS_SDK_PATH=${{ env.FLUTTER_ROOT }}" >> "$GITHUB_ENV"

  #     - name: Install Melos
  #       uses: bluefireteam/melos-action@v3

  #     - name: Run package tests
  #       run: melos run test:ci --no-select

  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v4
  #       with:
  #         token: ${{ secrets.CODECOV_TOKEN }}
  #         files: coverage/lcov.info
